name: PR

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
env:
  TERRAFORM_VERSION: 0.14.7

jobs:
  format:
    name: Terraform-Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
